[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "dist"

# Environment variables (set these in Netlify dashboard)
# Required secrets:
# - DATABASE_URL
# - FACEBOOK_APP_ID
# - FACEBOOK_APP_SECRET
# - INSTAGRAM_APP_ID
# - INSTAGRAM_APP_SECRET
# - SESSION_SECRET
# - OAUTH_BASE_URL (your Netlify URL, e.g., https://your-app.netlify.app)
