# Nixpacks configuration for Instaflow
# Forces devDependencies install for build tools (vite, esbuild),
# builds the app, prunes dev deps, then starts the server.

providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "5000"
HOST = "0.0.0.0"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build",
  "npm prune --omit=dev"
]

[start]
cmd = "node dist/index.js"
